version: "3.7"

services:
  postgres:
    ports:
      - 5432:5432

  pgadmin4:
    image: dpage/pgadmin4:latest
    networks:
      - database
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: e
      PGADMIN_DEFAULT_PASSWORD: e
    volumes:
      - pgadmin4-data:/var/lib/pgadmin

  hydra:
    ports:
      - 4445:4445

volumes:
  pgadmin4-data:
