version: "3.7"

services:
  postgres:
    restart: always
    build:
      context: ./docker/docker-postgresql-multiple-databases-master
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - database
      - hydra
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_MULTIPLE_DATABASES}

  redis:
    restart: always
    image: redis:alpine
    networks:
      - redis

  hydra:
    restart: always
    build:
      context: ./docker/hydra
    depends_on:
      - postgres
    networks:
      - hydra
    ports:
      - 4444:4444
    environment:
      - SECRETS_SYSTEM=${SECRETS_SYSTEM}
      - DSN=${DSN}
      - URLS_SELF_ISSUER=${URLS_SELF_ISSUER}
      - URLS_CONSENT=${URLS_CONSENT}
      - URLS_LOGIN=${URLS_LOGIN}
      - SERVE_PUBLIC_CORS_ALLOWED_ORIGINS=${HYDRA_CORS_ALLOWED_ORIGINS}

  oauth2backend:
    restart: always
    depends_on:
      - postgres
    build:
      context: ./oauth2/oauth2backend
    # ports:
    #   - ${OB_PORT}:${OB_PORT}
    networks:
      - hydra
      - database
      - frontend
    environment:
      - PORT=${OB_PORT}
      - HOST=${OB_HOST}
      - FRONT_ROOT=${OB_FRONT_ROOT}
      - HYDRA_ADMIN_URL=${HYDRA_ADMIN_URL}
      - NODE_TLS_REJECT_UNAUTHORIZED=${NODE_TLS_REJECT_UNAUTHORIZED}
      - SSO_MODE=${OB_SSO_MODE}

  oauth2frontend:
    restart: always
    build:
      context: ./oauth2/oauth2frontend
    networks:
      - frontend
    ports:
      - 80:80

  exam-front:
    restart: always
    build:
      context: ./exam/exam-front
    networks:
      - frontend
    ports:
      - 3000:3000

  exam-back:
    depends_on:
      - postgres
    restart: always
    networks:
      - database
      - hydra
    build:
      context: ./exam/exam-back
    environment:
      - HYDRA_ADMIN_URL=${HYDRA_ADMIN_URL}
      - NODE_TLS_REJECT_UNAUTHORIZED=${NODE_TLS_REJECT_UNAUTHORIZED}
      - TLA_URL=${EB_TLA_URL}

networks:
  database:
  hydra:
  frontend:
  redis:

volumes:
  postgres-data:
