version: "3.7"

services:
  postgres:
    ports:
      - 5432:5432
  redis:
    ports:
      - 6379:6379

  pgadmin4:
    restart: always
    build:
      context: ./docker/pgadmin4
    networks:
      - database
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: e
      PGADMIN_DEFAULT_PASSWORD: e
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    volumes:
      - pgadmin4-data:/var/lib/pgadmin

  hydra:
    ports:
      - 4445:4445

  exam-front:
    build:
      dockerfile: dev.Dockerfile
    working_dir: /app
    volumes:
      - ./exam/exam-front:/app
      - /app/node_modules
    environment:
      HOST: 0.0.0.0

  exam-back:
    build:
      dockerfile: dev.Dockerfile
    ports:
      - 3336:3000
    volumes:
      - ./exam/exam-back:/app
      - /app/node_modules


volumes:
  pgadmin4-data:
