# coding: utf-8

"""
    exam-back

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class NewRecord(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'answer': 'float',
        'start_time': 'str',
        'end_time': 'str',
        'timeline': 'list[str]'
    }

    attribute_map = {
        'answer': 'answer',
        'start_time': 'startTime',
        'end_time': 'endTime',
        'timeline': 'timeline'
    }

    def __init__(self, answer=None, start_time=None, end_time=None, timeline=None, local_vars_configuration=None):  # noqa: E501
        """NewRecord - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._answer = None
        self._start_time = None
        self._end_time = None
        self._timeline = None
        self.discriminator = None

        self.answer = answer
        self.start_time = start_time
        self.end_time = end_time
        self.timeline = timeline

    @property
    def answer(self):
        """Gets the answer of this NewRecord.  # noqa: E501


        :return: The answer of this NewRecord.  # noqa: E501
        :rtype: float
        """
        return self._answer

    @answer.setter
    def answer(self, answer):
        """Sets the answer of this NewRecord.


        :param answer: The answer of this NewRecord.  # noqa: E501
        :type: float
        """
        if self.local_vars_configuration.client_side_validation and answer is None:  # noqa: E501
            raise ValueError("Invalid value for `answer`, must not be `None`")  # noqa: E501

        self._answer = answer

    @property
    def start_time(self):
        """Gets the start_time of this NewRecord.  # noqa: E501


        :return: The start_time of this NewRecord.  # noqa: E501
        :rtype: str
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this NewRecord.


        :param start_time: The start_time of this NewRecord.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and start_time is None:  # noqa: E501
            raise ValueError("Invalid value for `start_time`, must not be `None`")  # noqa: E501

        self._start_time = start_time

    @property
    def end_time(self):
        """Gets the end_time of this NewRecord.  # noqa: E501


        :return: The end_time of this NewRecord.  # noqa: E501
        :rtype: str
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this NewRecord.


        :param end_time: The end_time of this NewRecord.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and end_time is None:  # noqa: E501
            raise ValueError("Invalid value for `end_time`, must not be `None`")  # noqa: E501

        self._end_time = end_time

    @property
    def timeline(self):
        """Gets the timeline of this NewRecord.  # noqa: E501


        :return: The timeline of this NewRecord.  # noqa: E501
        :rtype: list[str]
        """
        return self._timeline

    @timeline.setter
    def timeline(self, timeline):
        """Sets the timeline of this NewRecord.


        :param timeline: The timeline of this NewRecord.  # noqa: E501
        :type: list[str]
        """
        if self.local_vars_configuration.client_side_validation and timeline is None:  # noqa: E501
            raise ValueError("Invalid value for `timeline`, must not be `None`")  # noqa: E501

        self._timeline = timeline

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NewRecord):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NewRecord):
            return True

        return self.to_dict() != other.to_dict()
